# Site settings
title: Spark Jekyll Test

# URL settings
url: "https://LWN42.github.io"
baseurl: "" 

# Build settings
markdown: kramdown
permalink: pretty

# Theme settings
theme: jekyll-theme-cayman
